ngpu: 1
seed: 999
name: random-run

training:
  save_every: 500
  eval_every: 500
  print_every: 50

  checkpoint_dir: checkpoints

  num_iterations: 2400
  num_epochs: 50

  remote: 'wandb'
  log_freq: 100

  # Let's set to 1
  g_iter: 1
  d_iter: 1

data:
  name: facades
  channels: 3       # for color images, this is 3
  clone_again: False

  image_size: 64

  loader:
    batch_size: 128
    workers: 20


model:
  name: dcgan
  nz: 100
  ngf: 64
  ndf: 64

  wgan_weight_clip: 0.1


optimizer:
  name: adam
  lr: 0.0002
  beta1: 0.5
  beta2: 0.99